### PR TITLE
updated installation guide

### PR DESCRIPTION
**Pull request by dhaval055**

### CODE REVIEW

**Comment by frikky** [comment]
Thanks! Did you have the fix for the "export" part as well?

**Comment by dhaval055** [comment]
> Thanks! Did you have the fix for the "export" part as well?

Not yet. We ended up using the backend containers.

**Comment by frikky** [comment]
> > Thanks! Did you have the fix for the "export" part as well?
> 
> Not yet. We ended up using the backend containers.

But should it be removed?

**Comment by dhaval055** [comment]
> > > Thanks! Did you have the fix for the "export" part as well?
> > 
> > 
> > Not yet. We ended up using the backend containers.
> 
> But should it be removed?

yes, It works without the "export" on windows.

**Comment by dhaval055** [comment]
making another PR for the same

**Pull request closed without merging**
