### PR TITLE
fresh look for docs

### PR DESCRIPTION
**Pull request by yashsinghcodes**

### CODE REVIEW

**Comment by iiAnna** [comment]
Hey Yash, I am Anna and I help Shuffle with UI/UX.
It looks good but a few more details would help the page's readability.

- Adding location indicator on the right sidebar menu as the user scrolls along.
- Adding titles on top of the menu bars and if needed adding collapsables can help make the page look a lot cleaner.
- Make the menus take less space visually. For example, you can see how in MUI the menus look less significant compared to the content while in Shuffle, especially the right menu, takes a significant amount of attention.

image

image

You can take inspiration from Material UI and Bootstrap, they do a great job.

Great job, hope this helps! Let me know if you have any questions or comments.

**Comment by yashsinghcodes** [comment]
Thanks for the pointers, Anna. I'll make sure to address them in future commits :)

**Comment by yashsinghcodes** [comment]
Hi @iiAnna I'm working on the location indicator but this is how it is coming out, let me know what you think :)

**Comment by yashsinghcodes** [comment]
simplescreenrecorder-2024-05-10_09 34 59-ezgif com-video-to-gif-converter

**Comment by yashsinghcodes** [comment]
simplescreenrecorder-2024-05-10_10 44 19-ezgif com-video-to-gif-converter

**Comment by frikky** [comment]
🚀 
🔥

**Pull request merged**
