### PR TITLE
Fix dockerbuild github action

### PR DESCRIPTION
**Pull request by SainiAditya1**
the workflow should run if the changes made are in folders or files other than the .github folder and .md files. https://github.com/Shuffle/Shuffle/issues/1242 . I have tested it and it is working fine.

### CODE REVIEW

**Comment by SainiAditya1** [comment]
@frikky

**Comment by SainiAditya1** [comment]
Hey @frikky , Please review this PR..

**Comment by 0x0elliot** [comment]
let's see

**Comment by 0x0elliot** [comment]
let me test this really quickly

**Comment by 0x0elliot** [comment]
thanks for your contribution!

**Pull request merged**
