### PR TITLE
Fix Dockerbuild GitHub actions. 

### PR DESCRIPTION
**Pull request by imlakshay08**
Solves #1242 

I added the paths-ignore option under the on section to specify that changes to markdown files (**.md) should be ignored, preventing the action from running for these files.

### CODE REVIEW

**Comment by 0x0elliot** [comment]
hey lakshay, this PR doesn't work. look, it clearly runs :): https://github.com/imlakshay08/Shuffle/actions/runs/6755071602/job/18363154277

https://stackoverflow.com/questions/71070064/github-workflow-excluding-paths-does-not-work probably because of this. i am closing it because you didn't ask and stepped a toe!

**Comment by imlakshay08** [comment]
Thank you for the review. I'll test it again.

**Comment by 0x0elliot** [comment]
let this one be! I have assigned it to @sainiaditya1 for now. 

let's find you another issue.

**Comment by imlakshay08** [comment]
> let this one be! I have assigned it to @SainiAditya1 for now.
> 
> let's find you another issue.

Alright. 
Actually I have applied for that GitHub Octernship so I think I might need guidance for that. Hang on, I'll ping you on discord.

**Pull request closed without merging**
