### PR TITLE
Create feedback module

### PR DESCRIPTION
**Pull request by dassudip2001**
Create a feedback button and click the feedback button and generate a unique link every time and open the feedback form.

Using Email.js to send a emails cheange credential to send the email

### CODE REVIEW

**Comment by frikky** [comment]
Hello, and thanks for the PR!

I do have to ask though; 
- what do you think we should do with this? 
- Who is it for? 
- How does it work in an on-premises environment?

PS: We don't use CSS modules, but instead inline CSS, so if we end up using this, we'll need you to move the Design.css into the actual code.

**Comment by dassudip2001** [comment]
I am trying to implement 
1. in a navbar section create a button or link to generate a random URL and send the link to other people to get the feedback and show the feedback in an admin section. I mean who is creating the link.
2. Also used this form for feedback on the Shuffle services.



also, I am interested in the Shuffle  project to contribute

**Comment by dassudip2001** [comment]
@frikky it is possible to implement these features

**Comment by frikky** [comment]
> @frikky it is possible to implement these features. I am interested in implementing these features

These features are not necessary, and in my opinion don't fit in well with how we are building Shuffle at the moment. Feedback is good, a random one with the requirement of 3rd party API's dont fit the bill :)

**Pull request closed without merging**
