### PR TITLE
Fix swarm timeout between orborus and worker hosted on separate nodes

### PR DESCRIPTION
**Pull request by 0x0elliot**
https://github.com/orgs/Shuffle/projects/8/views/47

### CODE REVIEW

**Comment by 0x0elliot** [comment]
yet to be tested. please test before merging.

**Comment by 0x0elliot** [comment]
https://github.com/Shuffle/Shuffle-docs/pull/171 please close as you close this.

**Comment by 0x0elliot** [comment]
my concerns i would want you to review start here: https://github.com/Shuffle/Shuffle/blob/fddca0146a5745b34a27d2823d1186ef804e7b12/functions/onprem/orborus/orborus.go#L227

my assumption is that in the container, the first network interface after loopback is the best way to spot the docker bridge network. this is an observation i made. i don't know when it would change. you will have to give some feedback on the consistency of this.

i am also thinking of checking once if the network interface contains "eth0" since it does till a certain part.

**Review by frikky — COMMENTED** [review]
Submit review!!

**Comment by 0x0elliot** [comment]
Would test this and make sure it's somewhat ready for prod. Be ready to see it break however. Quite unsure about the network interface naming.

**Comment by 0x0elliot** [comment]
This definitely makes me feel more confident in nothing messing up.

**Comment by 0x0elliot** [comment]
Ready for merge. Let's break things.

**Comment by 0x0elliot** [comment]
ready

**Comment by frikky** [comment]
Looks better! Covering all bases with a fallback

**Pull request merged**
