### PR TITLE
Improve app builder

### PR DESCRIPTION
**Pull request by P4sca1**
This PR fixes some issues I noticed with the app builder on the 2.0.0 branch.
I split my changes into 4 commits to make this PR more readable.

**go mod tidy**
This Commit is the result of running `go mod tidy` which just removes old references in the `go.sum` file.

**Use NodeName instead of NodeSelector**
I noticed that the `shuffle-app-builder` pod was not able to find a node in my k3s test cluster. This is because it expects the `node` label to be set. This is a non-standard label that is not always present. I changed the code to use `NodeName` instead. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename.

**Fix --dockerfile flag**
Kaniko crashes with the following error: `Error: error resolving dockerfile path: please provide a valid path to a Dockerfile within the build context with --dockerfile`.
The `--dockerfile` flag was set to `./Dockerfile`. It should either use an absolute path or a path relative to the build context in which case the `./` prefix needs to be removed. When using the `./` prefix, the path is relative to the current working directory when kaniko gets executed, and not relative to the build context.

**Use filepath module for constructing contextDir**
I noticed that file paths are manipulated using string functions. I changed the code to use the methods from the `filepath` module which should be more resilient and easier to read.
I also renamed `dockerfileFolder` to `dockerfileLocation`, because the variable point to the `Dockerfile` and not to the folder in which the `Dockerfile` lives.

### CODE REVIEW

**Comment by frikky** [comment]
Oh, this is cool - thanks @P4sca1

**Comment by frikky** [comment]
One of the things we gotta build into this is to do automatic image distribution to active Orborus queues, as to ensure they get the latest image in realtime. There is also some kind of caching issue for users loading apps that causes this to not work as well as expected

@ayush0033 can you test it out? :)

**Comment by P4sca1** [comment]
For Kubernetes, `ImagePullPolicy` could be set to `Always` and App Deployments could be restarted when a new version gets build.  Alternatively, image digests could be used instead of tags to target a specific image version explicitly. The deployment could then be updated with the new digest after building.

**Comment by frikky** [comment]
> For Kubernetes, `ImagePullPolicy` could be set to `Always` and App Deployments could be restarted when a new version gets build. Alternatively, image digests could be used instead of tags to target a specific image version explicitly. The deployment could then be updated with the new digest after building.

Problem with "Always" pulls is that it will by default resort to downloads from our Dockerhub, causing possible overrides of local changes unless a local Docker registry is set up

**Comment by 0x0elliot** [comment]
I am going to approve and test out the nightly build for this in my cluster. This looks good to me.

**Comment by P4sca1** [comment]
I just tested the latest nightly build and most of the applied fixes work correctly. The exception is the --dockerfile flag, which still leads to issues. I will investigate further and create a follow-up PR.

**Pull request merged**
